# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181229_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_hash',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_otp',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
