# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181230_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='assets/images/demo/users/face11.jpg', max_length=800, null=True),
        ),
    ]
