# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-04 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='Cyberwatch', max_length=800, null=True),
        ),
    ]
