# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='N/A', max_length=20, null=True),
        ),
    ]
