# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-05 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
