# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-25 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
